#
# Basic settings.
#
url: http://apophis.cz
title: Honza "apophis" Horáček
description: Osobní prezentace.
avatar: /assets/img/avatar.jpg
favicon: /assets/img/favicon.ico
language: cs
author: Jan Horáček
keywords: Jan,Horáček,web,osobní
robots: index,follow

#
# Icons
#
icons:
  rss: true
  email:
  github: ttskch
  bitbucket:
  twitter: ttskch
  facebook:
  google_plus:
  tumblr:
  behance:
  dribbble:
  flickr:
  instagram:
  linkedin: # full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange: # full URL
  steam:
  wordpress:
  youtube:

#
# Prettify url.
#
permalink: pretty

#
# Gems.
#
plugins:
  - jekyll-paginate
  - jemoji

#
# Styles: see "_sass/base/_variables.scss"
#

#
# !! Danger zone !!
#

include: ["_pages", ".htaccess"]

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

excerpt_separator: <!--more-->

sass:
  sass_dir: _sass
  style: :compressed # or :expanded

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor
